contact:
  name: Oleg Grigorijan
  url: https://github.com/oleg-grigorijan/
  email: oleg.grigorijan@gmail.com

spring:
  application:
    name: budgetgo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/budgetgo?createDatabaseIfNotExist=true&useUnicode=yes&serverTimezone=GMT%2B3
    password: password
    username: admin
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

hibernate:
  hbm2ddl.auto: validate
  dialect: org.hibernate.dialect.MySQL8Dialect
  show_sql: true
  format_sql: true

server.port: 8080

cors:
  allowedOrigins: http://localhost:4200, http://localhost:4201
  allowedMethods: GET, HEAD, POST, PATCH, DELETE, OPTIONS
  allowedHeaders: "*"
  allowCredentials: true

logging:
  file:
    path: /local
    name: ${spring.application.name}.log

springfo.documentation.swagger.v2.path: /api/docs
