INSERT INTO BUDGETGO_TEST.PUBLIC.STORAGES (ID, NAME, DESCRIPTION, CURRENCY_ID, BALANCE, INITIAL_BALANCE)
VALUES (1, 'Personal Card', 'My personal card', 1, 1000, 1000);
INSERT INTO BUDGETGO_TEST.PUBLIC.STORAGES_RELATIONS (STORAGE_ID, USER_ID, USER_ROLE, INVITER_ID, IS_INVITATION, IS_INCLUDED_IN_USER_STATISTICS)
VALUES (1, 1, 'CREATOR', 1, false, true);

INSERT INTO BUDGETGO_TEST.PUBLIC.STORAGES (ID, NAME, DESCRIPTION, CURRENCY_ID, BALANCE, INITIAL_BALANCE)
VALUES (2, 'Shared Budget', '', 2, 20000, 20000);
INSERT INTO BUDGETGO_TEST.PUBLIC.STORAGES_RELATIONS (STORAGE_ID, USER_ID, USER_ROLE, INVITER_ID, IS_INVITATION, IS_INCLUDED_IN_USER_STATISTICS)
VALUES (2, 1, 'CREATOR', 1, false, true);
INSERT INTO BUDGETGO_TEST.PUBLIC.STORAGES_RELATIONS (STORAGE_ID, USER_ID, USER_ROLE, INVITER_ID, IS_INVITATION, IS_INCLUDED_IN_USER_STATISTICS)
VALUES (2, 2, 'ADMIN', 1, false, true);
INSERT INTO BUDGETGO_TEST.PUBLIC.STORAGES_RELATIONS (STORAGE_ID, USER_ID, USER_ROLE, INVITER_ID, IS_INVITATION, IS_INCLUDED_IN_USER_STATISTICS)
VALUES (2, 3, 'EDITOR', 1, true, false);
INSERT INTO BUDGETGO_TEST.PUBLIC.STORAGES_RELATIONS (STORAGE_ID, USER_ID, USER_ROLE, INVITER_ID, IS_INVITATION, IS_INCLUDED_IN_USER_STATISTICS)
VALUES (2, 4, 'VIEWER', 2, false, true);
