DELETE
FROM BUDGETGO_TEST.PUBLIC.OPERATIONS_KEY_SEQUENCE;

DELETE
FROM BUDGETGO_TEST.PUBLIC.OPERATIONS;

DELETE
FROM BUDGETGO_TEST.PUBLIC.USER_CATEGORIES;

DELETE
FROM BUDGETGO_TEST.PUBLIC.CATEGORIES;

DELETE
FROM BUDGETGO_TEST.PUBLIC.STORAGES_RELATIONS;

DELETE
FROM BUDGETGO_TEST.PUBLIC.STORAGES;

DELETE
FROM BUDGETGO_TEST.PUBLIC.USERS;

DELETE
FROM BUDGETGO_TEST.PUBLIC.CURRENCIES;
